version: 2.1
description: Expo setup for React Native

orbs:
  expo: ryanpedersen/expo@0.1.0

executors:
  node:
    docker:
      - image: cimg/node:14.0.0

jobs:
  test:
    executor: node
    parallelism: 2
    steps:
      - checkout
      - expo/expo-auth
      - restore_cache:
          keys:
            - node-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-cache-v1-{{ .Branch }}-
            - node-cache-v1-
      - run:
          name: Fetch dependencies
          command: npm install
      - save_cache:
          paths:
            - ~/.npm
            - ~/.cache
          key: node-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: 
          name: Check for parallelism
          command: |
            if [ $NODE_TOTAL -ne 2 ]; then
              echo "Need to have parallelism set to 2"
              exit 1
            fi
      - run: 
          command: |
            if [ $CIRCLE_NODE_INDEX -eq 0 ]; then
              npx expo-cli build:android --release-channel production --non-interactive --no-publish 
            elif [[ $CIRCLE_NODE_INDEX -eq 1 ]]; then
              npx expo-cli build:ios --release-channel production --non-interactive --no-publish 
            fi
          no_output_timeout: '30m'   
  expo_build_and_get_ipa:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-cache-v1-{{ .Branch }}-
            - node-cache-v1-
      - run:
          name: Fetch dependencies
          command: npm install
      - save_cache:
          paths:
            - ~/.npm
            - ~/.cache
          key: node-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - expo/expo-auth
      - expo/expo-build
      - expo/get-ios-ipa
  expo_get_ipa:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-cache-v1-{{ .Branch }}-
            - node-cache-v1-
      - run:
          name: Fetch dependencies
          command: npm install
      - save_cache:
          paths:
            - ~/.npm
            - ~/.cache
          key: node-cache-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - expo/expo-auth
      - expo/get-ios-ipa
      - store_artifacts:
          path: ~/project/app.ipa

workflows:
  build_expo:
    jobs:
      - test
      # - expo_build_and_get_ipa
      # - expo_get_ipa
